//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirror_Play
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermeta
    {
        public long umeta_id { get; set; }
        public long user_id { get; set; }
        public string meta_key { get; set; }
        public string meta_value { get; set; }
    }
}
